version: '3.1'

services:
  postgres:
    image: postgres:15.3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5423:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
